package net.practicalcoding.recyclerviewyt

enum class MoleculeId {
    ALANINE, ARGININE, ASPARAGINE, ASPARTIC_ACID, CYSTEINE, GLUTAMIC_ACID, GLUTAMINE, GLYCINE,
    HISTIDINE, ISOLEUCINE, LEUCINE, LYSINE, METHIONINE, PHENYLALANINE, PROLINE, SERINE, THREONINE,
    TRYPTOPHAN, TYROSINE, VALINE
}